import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CartModal from "@/components/Modal/CartModal";
import ToasterProvider from "@/Others/ToastProvider";
import NavWrapper from "@/components/navbar/NavWrapper";
import OTPModal from "@/components/Modal/OTPModal";
import RecentlyViewed from "@/components/RecentlyViewed";
import WishlistModal from "@/components/Modal/WishlistModal";
import AddToWishlistModal from "@/components/Modal/AddToWishlistModal";
import Intro from "@/components/Intro";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ShopEzy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider />
        <Intro/>
        <NavWrapper />
        <AddToWishlistModal/>
        <WishlistModal/>
        <OTPModal />
        <CartModal />
        {children}
        <RecentlyViewed/>
      </body>
    </html>
  );
}
